config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users

  resources :tasks do
    collection do
      post :confirm
    end
  end

  resources :sessions

  namespace :admin do
    resources :users
  end

  resources :labels
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mannyou2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "user_body">
    <header>
      <h1 class="bg-dark text-white py-1"><%= link_to t('.Tasks_index'), tasks_path %></h1>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    </header>

    <% if logged_in? %>
      <p class = "current_user_p">【現在のログインユーザー】<%= current_user.name %></p>
      <%= link_to t('.user_page'), user_path(current_user.id) %>：

      <% if current_user.admin? %>
        <%= link_to t('.user_manage'), admin_users_path %>：
        <%= link_to t('.new_account_create'), new_admin_user_path %>：
      <% end %>

      <%= link_to t('.label_list'), labels_path %>：
      <%= link_to t('.logged_out'), session_path(current_user.id), method: :delete %>

    <% else %>
      <%= link_to t('.new_account'), new_user_path %>：
      <%= link_to t('.logged_in'), new_session_path %>
    <% end %>

    <%= yield %>

  </body>
  <footer class="footer_copy">
    © タスク管理master
  </footer>
</html>